# Generated by Django 3.2.9 on 2021-12-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Github', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('RepositoryURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_type', models.CharField(choices=[('CL', 'closed'), ('OP', 'opened')], max_length=10)),
                ('IssueOpenCount', models.IntegerField(blank=True, null=True)),
                ('IssueCloseCount', models.IntegerField(blank=True, null=True)),
                ('OpenTime', models.DateField()),
                ('CloseTime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RepositoryURL', models.URLField()),
                ('User', models.ManyToManyField(to='register.User')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='Project',
            field=models.ManyToManyField(to='dashboard.Project'),
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('CommitCount', models.IntegerField(blank=True, null=True)),
                ('Time', models.DateField(primary_key=True, serialize=False)),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AllIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_type', models.CharField(choices=[('CL', 'closed'), ('OP', 'opened')], max_length=10)),
                ('Time', models.DateField()),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('closedCount', models.IntegerField(blank=True, null=True)),
                ('openedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AllCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
    ]
