# Generated by Django 3.2.9 on 2021-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('Github', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('State', models.BooleanField()),
                ('RepositoryURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='Project',
            field=models.ManyToManyField(to='dashboard.Project'),
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangedFileCount', models.IntegerField(blank=True, null=True)),
                ('AdditionCount', models.IntegerField(blank=True, null=True)),
                ('DeletionCount', models.IntegerField(blank=True, null=True)),
                ('Time', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ClosedIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateField()),
                ('CloseTime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('ChartType', models.CharField(choices=[('2', 'StackedBarChart'), ('3', 'PieChart'), ('4', 'LineChart'), ('1', 'BarChart')], max_length=10)),
                ('DataType', models.CharField(max_length=50)),
                ('DataDetailType', models.CharField(max_length=100)),
                ('HasProject', models.ManyToManyField(related_name='HasProject', to='dashboard.Project')),
                ('User', models.ManyToManyField(to='register.User')),
                ('project', models.ManyToManyField(related_name='Project', to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AllIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('closedCount', models.IntegerField(blank=True, null=True)),
                ('openedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AllCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('committedCount', models.IntegerField(blank=True, null=True)),
                ('changedCount', models.IntegerField(blank=True, null=True)),
                ('addedCount', models.IntegerField(blank=True, null=True)),
                ('deletedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
    ]
