# Generated by Django 3.2.9 on 2021-12-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('ChartType', models.CharField(choices=[('3', 'PieChart'), ('4', 'LineChart'), ('1', 'BarChart'), ('2', 'StackedBarChart')], max_length=10)),
                ('DataType', models.CharField(max_length=50)),
                ('DataDetailType', models.CharField(max_length=100)),
                ('TimeScale', models.CharField(max_length=20)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('Github', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('State', models.BooleanField()),
                ('RepositoryURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='YearIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('closedCount', models.IntegerField(blank=True, null=True)),
                ('openedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='YearCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('committedCount', models.IntegerField(blank=True, null=True)),
                ('changedCount', models.IntegerField(blank=True, null=True)),
                ('addedCount', models.IntegerField(blank=True, null=True)),
                ('deletedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.TextField()),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('Chart', models.ManyToManyField(to='dashboard.Chart')),
                ('User', models.ManyToManyField(to='register.User')),
            ],
        ),
        migrations.CreateModel(
            name='OpenIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MonthIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('closedCount', models.IntegerField(blank=True, null=True)),
                ('openedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MonthCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('committedCount', models.IntegerField(blank=True, null=True)),
                ('changedCount', models.IntegerField(blank=True, null=True)),
                ('addedCount', models.IntegerField(blank=True, null=True)),
                ('deletedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DayIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('closedCount', models.IntegerField(blank=True, null=True)),
                ('openedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DayCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('committedCount', models.IntegerField(blank=True, null=True)),
                ('changedCount', models.IntegerField(blank=True, null=True)),
                ('addedCount', models.IntegerField(blank=True, null=True)),
                ('deletedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='Project',
            field=models.ManyToManyField(to='dashboard.Project'),
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangedFileCount', models.IntegerField(blank=True, null=True)),
                ('AdditionCount', models.IntegerField(blank=True, null=True)),
                ('DeletionCount', models.IntegerField(blank=True, null=True)),
                ('Time', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ClosedIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateField()),
                ('CloseTime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='HasProject',
            field=models.ManyToManyField(related_name='HasProject', to='dashboard.Project'),
        ),
        migrations.AddField(
            model_name='chart',
            name='User',
            field=models.ManyToManyField(to='register.User'),
        ),
        migrations.AddField(
            model_name='chart',
            name='project',
            field=models.ManyToManyField(related_name='Project', to='dashboard.Project'),
        ),
    ]
