# Generated by Django 3.2.9 on 2021-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(choices=[('2', 'StackedBarChart'), ('3', 'PieChart'), ('1', 'BarChart'), ('4', 'LineChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chart',
            name='DataType',
            field=models.CharField(choices=[('add', 'Add'), ('delete', 'Delete'), ('open', 'Open'), ('commit', 'Commit'), ('close', 'Close'), ('changed', 'Changed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='closedissuerecord',
            name='CloseTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='closedissuerecord',
            name='Opentime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commitrecord',
            name='Time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='openissuerecord',
            name='Opentime',
            field=models.DateField(),
        ),
    ]
