# Generated by Django 3.2.9 on 2021-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_user_github'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Diagram_type', models.CharField(choices=[('SBarC', 'StackedBarChart'), ('BarC', 'BarChart'), ('PIEC', 'PieChart')], max_length=10)),
                ('horizontal_axis_name', models.CharField(max_length=20)),
                ('vertical_axis_name', models.CharField(max_length=20)),
                ('PID', models.ManyToManyField(to='dashboard.Project')),
                ('User', models.ManyToManyField(to='register.User')),
            ],
        ),
        migrations.RenameField(
            model_name='commitrecord',
            old_name='CommitCount',
            new_name='AdditionCount',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='RepositoryURL',
        ),
        migrations.AddField(
            model_name='commitrecord',
            name='ChangedFileCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitrecord',
            name='DeletionCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='PID',
            field=models.ManyToManyField(to='dashboard.Project'),
        ),
        migrations.AlterField(
            model_name='allissue',
            name='Issue_type',
            field=models.CharField(choices=[('OP', 'opened'), ('CL', 'closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='Issue_type',
            field=models.CharField(choices=[('OP', 'opened'), ('CL', 'closed')], max_length=10),
        ),
        migrations.CreateModel(
            name='DiagramValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Key', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('Diagram', models.ManyToManyField(to='dashboard.Diagram')),
            ],
        ),
    ]
