# Generated by Django 3.2.9 on 2021-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(choices=[('2', 'StackedBarChart'), ('1', 'BarChart'), ('4', 'LineChart'), ('3', 'PieChart')], max_length=10),
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ManyToManyField(to='register.User')),
                ('project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
    ]
