# Generated by Django 3.2.9 on 2021-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211214_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitrecord',
            name='Time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('BarC', 'BarChart'), ('SBarC', 'StackedBarChart'), ('PIEC', 'PieChart')], max_length=10),
        ),
    ]
