# Generated by Django 3.2.9 on 2021-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211217_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(choices=[('3', 'PieChart'), ('4', 'LineChart'), ('1', 'BarChart'), ('2', 'StackedBarChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chart',
            name='DataType',
            field=models.CharField(choices=[('commit', 'Commit'), ('open', 'Open'), ('changed', 'Changed'), ('add', 'Add'), ('close', 'Close'), ('delete', 'Delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chart',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
