# Generated by Django 3.2.9 on 2021-12-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211214_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allissue',
            name='Issue_type',
            field=models.CharField(choices=[('CL', 'closed'), ('OP', 'opened')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('SBarC', 'StackedBarChart'), ('BarC', 'BarChart'), ('PIEC', 'PieChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='Issue_type',
            field=models.CharField(choices=[('CL', 'closed'), ('OP', 'opened')], max_length=10),
        ),
        migrations.DeleteModel(
            name='CommitRecord',
        ),
    ]
