# Generated by Django 3.2.9 on 2021-12-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211218_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedissuerecord',
            old_name='CloseTime',
            new_name='Closetime',
        ),
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(choices=[('3', 'PieChart'), ('1', 'BarChart'), ('2', 'StackedBarChart'), ('4', 'LineChart')], max_length=10),
        ),
    ]
