# Generated by Django 3.2.9 on 2021-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211216_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('PIEC', 'PieChart'), ('BarC', 'BarChart'), ('SBarC', 'StackedBarChart')], max_length=10),
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangedFileCount', models.IntegerField(blank=True, null=True)),
                ('AdditionCount', models.IntegerField(blank=True, null=True)),
                ('DeletionCount', models.IntegerField(blank=True, null=True)),
                ('Time', models.DateTimeField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
    ]
