# Generated by Django 3.2.9 on 2021-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211218_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPullrequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateField()),
                ('Closetime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DayPullrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('openedCount', models.IntegerField(blank=True, null=True)),
                ('closedCount', models.IntegerField(blank=True, null=True)),
                ('mergedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MergedPullrequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateField()),
                ('Mergetime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPullrequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='yearissue',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='CreatedTime',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='DataDetailType',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='HasProject',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='User',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='project',
        ),
        migrations.RemoveField(
            model_name='dayissue',
            name='Count',
        ),
        migrations.AddField(
            model_name='chart',
            name='CheckBox',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='Position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='TimeScale',
            field=models.CharField(blank=True, default='day', max_length=20),
        ),
        migrations.DeleteModel(
            name='MonthIssue',
        ),
        migrations.DeleteModel(
            name='YearIssue',
        ),
    ]
