# Generated by Django 3.2.9 on 2021-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211216_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateTimeField()),
                ('CloseTime', models.DateTimeField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='OpenIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opentime', models.DateTimeField()),
                ('Contributor', models.ManyToManyField(to='dashboard.Contributor')),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='IssueRecord',
        ),
    ]
