# Generated by Django 3.2.9 on 2021-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211216_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allissue',
            name='Issue_type',
            field=models.CharField(choices=[('OP', 'opened'), ('CL', 'closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('SBarC', 'StackedBarChart'), ('PIEC', 'PieChart'), ('BarC', 'BarChart'), ('LINC', 'LineChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='Issue_type',
            field=models.CharField(choices=[('OP', 'opened'), ('CL', 'closed')], max_length=10),
        ),
    ]
