# Generated by Django 3.2.9 on 2021-12-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211216_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allissue',
            name='Issue_type',
            field=models.CharField(choices=[('CL', 'closed'), ('OP', 'opened')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('PieC', 'PieChart'), ('LineC', 'LineChart'), ('BarC', 'BarChart'), ('SBarC', 'StackedBarChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='Issue_type',
            field=models.CharField(choices=[('CL', 'closed'), ('OP', 'opened')], max_length=10),
        ),
    ]
