# Generated by Django 3.2.9 on 2021-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_chart_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.TextField(blank=True, default='亲亲，该仓库暂时没有项目简介噢~', null=True),
        ),
    ]
