# Generated by Django 3.2.9 on 2021-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211216_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('LineC', 'LineChart'), ('BarC', 'BarChart'), ('PieC', 'PieChart'), ('SBarC', 'StackedBarChart')], max_length=10),
        ),
    ]
