# Generated by Django 3.2.9 on 2021-12-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211216_1552'),
        ('dashboard', '0008_alter_diagram_diagram_type'),
    ]

    operations = [
    ]
