# Generated by Django 3.2.9 on 2021-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211216_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='PID',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='User',
        ),
        migrations.RemoveField(
            model_name='diagramvalue',
            name='Diagram',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='PID',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='User',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='Name',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='Github',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AllIssue',
        ),
        migrations.DeleteModel(
            name='Diagram',
        ),
        migrations.DeleteModel(
            name='DiagramValue',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
