# Generated by Django 3.2.9 on 2021-12-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211216_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedissuerecord',
            old_name='CloseTime',
            new_name='Closetime',
        ),
        migrations.AlterField(
            model_name='allissue',
            name='Issue_type',
            field=models.CharField(choices=[('OP', 'opened'), ('CL', 'closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('PieC', 'PieChart'), ('SBarC', 'StackedBarChart'), ('LineC', 'LineChart'), ('BarC', 'BarChart')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
