# Generated by Django 3.2.9 on 2021-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211216_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='Github',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='Diagram_type',
            field=models.CharField(choices=[('SBarC', 'StackedBarChart'), ('LineC', 'LineChart'), ('BarC', 'BarChart'), ('PieC', 'PieChart')], max_length=10),
        ),
    ]
