# Generated by Django 3.2.9 on 2021-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_identifyingcode'),
        ('dashboard', '0011_auto_20211216_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('ChartType', models.CharField(choices=[('1', 'BarChart'), ('2', 'StackedBarChart'), ('3', 'PieChart'), ('4', 'LineChart')], max_length=10)),
                ('DataType', models.CharField(choices=[('2', 'Changed'), ('3', 'Add'), ('4', 'Delete'), ('6', 'Close'), ('5', 'Open'), ('1', 'Commit')], max_length=10)),
                ('HasProject', models.ManyToManyField(related_name='HasProject', to='dashboard.Project')),
                ('User', models.ManyToManyField(to='register.User')),
                ('project', models.ManyToManyField(related_name='Project', to='dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AllIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('closedCount', models.IntegerField(blank=True, null=True)),
                ('openedCount', models.IntegerField(blank=True, null=True)),
                ('Project', models.ManyToManyField(to='dashboard.Project')),
            ],
        ),
    ]
