# Generated by Django 3.2.9 on 2021-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_allissue_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='State',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(choices=[('2', 'StackedBarChart'), ('1', 'BarChart'), ('3', 'PieChart'), ('4', 'LineChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chart',
            name='DataType',
            field=models.CharField(choices=[('6', 'Close'), ('3', 'Add'), ('2', 'Changed'), ('4', 'Delete'), ('1', 'Commit'), ('5', 'Open')], max_length=10),
        ),
    ]
