# Generated by Django 3.2.9 on 2021-12-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20211216_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(choices=[('3', 'PieChart'), ('4', 'LineChart'), ('1', 'BarChart'), ('2', 'StackedBarChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chart',
            name='DataType',
            field=models.CharField(choices=[('add', 'Add'), ('open', 'Open'), ('delete', 'Delete'), ('changed', 'Changed'), ('commit', 'Commit'), ('close', 'Close')], max_length=10),
        ),
    ]
