# Generated by Django 3.2.9 on 2021-12-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211216_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='ChartType',
            field=models.CharField(choices=[('3', 'PieChart'), ('1', 'BarChart'), ('4', 'LineChart'), ('2', 'StackedBarChart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chart',
            name='DataType',
            field=models.CharField(max_length=15),
        ),
    ]
