# Generated by Django 3.2.9 on 2021-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifyingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('User', models.ManyToManyField(to='register.User')),
            ],
        ),
    ]
