# Generated by Django 3.2.9 on 2021-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_user_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('User', models.ManyToManyField(to='register.User')),
            ],
        ),
    ]
